server:
  port: 8083
spring:
  application:
    name: friend-web
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/wechat
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.itmv.entity